apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: nginx-proxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-proxy
        version: v1
    spec:
      containers:
      - name: nginx-proxy
        image: josedrojasa/nginx-thesis-path-split:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80


