apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-activemq
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: activemq
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

