apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  labels:
    app: activemq-service
spec:
  type: NodePort
  ports:
  - port: 8161
    name: http
  - port: 61616
    name: activemq
  selector:
    app: activemq

