apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-mysql-istio
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: mysql
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

